services:
  web:
    build: .
    image: fempo_php_custom
    container_name: fempo_web
    #user: "${UID}:${GID}"
    volumes:
      - /home/marti/docker/fempo/web:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: fempo_db
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: fempo
      MYSQL_USER: iesemili
      MYSQL_PASSWORD: <password>
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fempo_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: iesemili
      PMA_PASSWORD: <password>
    ports:
      - "8082:80"
    restart: always

volumes:
  db_data:
